-- Veri tabani olusturuyoruz.
CREATE SCHEMA `my_company_db` DEFAULT CHARACTER SET utf32 COLLATE utf32_bin ;


-- DROP TABLE `my_company_db`.`CUSTOMERS`;
-- Müsteriler Tablosu
CREATE TABLE `my_company_db`.`CUSTOMERS` (
                                             `ID` INT NOT NULL AUTO_INCREMENT,
                                             `FIRST_NAME` VARCHAR(60) NULL,
                                             `LAST_NAME` VARCHAR(60) NULL,
                                             PRIMARY KEY (`ID`));

-- Tabloyu siler burada "products"
-- DROP TABLE `my_company_db`.`products`;

-- Ürünler Tablosu
CREATE TABLE `my_company_db`.`products` (
                                            `ID` INT NOT NULL AUTO_INCREMENT,
                                            `PROD_NAME` VARCHAR(45) NULL,
                                            `PROD_CODE` VARCHAR(45) NULL,
                                            PRIMARY KEY (`ID`));

-- tablo üzerinde degisiklik yapar
ALTER TABLE `my_company_db`.`products`
    CHANGE COLUMN `PROD_CODE` `PROD_Code` VARCHAR(45) NULL DEFAULT NULL ;

-- DROP DATABASE --> Database(Schema yi) i siler (Veritabanini)
-- DROP DATABASE `my_company_db`;

-- Müsteri tablosuna kayitlar eklendi
INSERT INTO `my_company_db`.`CUSTOMERS` (`FIRST_NAME`, `LAST_NAME`) VALUES ('Hakan', 'Metin');
INSERT INTO `my_company_db`.`CUSTOMERS` (`FIRST_NAME`, `LAST_NAME`) VALUES ('Natalie', 'Weiss');
INSERT INTO `my_company_db`.`CUSTOMERS` (`FIRST_NAME`, `LAST_NAME`) VALUES ('Martin', 'Lol');


-- MUSTERILERI LISTELE
SELECT * FROM my_company_db.CUSTOMERS;

-- Sadece 1 Kayit
INSERT INTO `my_company_db`.`CUSTOMERS`
(
    `FIRST_NAME`,`LAST_NAME`)
VALUES('Tuana', 'Kaymaz');

-- Sadece 1 Kayit
INSERT INTO my_company_db.CUSTOMERS
(FIRST_NAME,LAST_NAME)
VALUES('Mike', 'Yes');

-- MUSTERILERI LISTELE
SELECT * FROM my_company_db.CUSTOMERS;


-- TABLOYA 2 TANE YENI KOLON EKLEDIK VE 2 KOLON ÜZERINDE DEGISIKLIK YAPILDI
ALTER TABLE `my_company_db`.`CUSTOMERS`
    ADD COLUMN `AGE` SMALLINT(3) NULL AFTER `LAST_NAME`,
    ADD COLUMN `COUNTRY` VARCHAR(65) NULL AFTER `AGE`,
    CHANGE COLUMN `ID` `CUSTOMER_ID` INT NOT NULL AUTO_INCREMENT ,
    CHANGE COLUMN `FIRST_NAME` `FIRST_NAME` VARCHAR(70) NULL DEFAULT NULL ;

-- TABLODA YENI EKLENEN KOLONLARA DEGER GIRILDI
UPDATE `my_company_db`.`CUSTOMERS` SET `AGE` = '29', `COUNTRY` = 'TR' WHERE (`CUSTOMER_ID` = '1');
UPDATE `my_company_db`.`CUSTOMERS` SET `AGE` = '32', `COUNTRY` = 'DE' WHERE (`CUSTOMER_ID` = '2');
UPDATE `my_company_db`.`CUSTOMERS` SET `AGE` = '23', `COUNTRY` = 'BR' WHERE (`CUSTOMER_ID` = '3');
UPDATE `my_company_db`.`CUSTOMERS` SET `AGE` = '35', `COUNTRY` = 'USA' WHERE (`CUSTOMER_ID` = '4');
UPDATE `my_company_db`.`CUSTOMERS` SET `AGE` = '38', `COUNTRY` = 'BR' WHERE (`CUSTOMER_ID` = '5');


-- MUSTERILERI LISTELE
SELECT * FROM my_company_db.CUSTOMERS;


-- SADECE 3 KOLON SECILDI
SELECT CUSTOMER_ID,FIRST_NAME, CUSTOMERS.LAST_NAME FROM my_company_db.CUSTOMERS;

-- ULKESI BR OLAN MÜSTERILERI GETIR
SELECT *
FROM my_company_db.CUSTOMERS
WHERE COUNTRY = 'BR';

-- ULKESI BR OLAN ve Ismide "Metin" olan MÜSTERILERI GETIR
SELECT *
FROM my_company_db.CUSTOMERS
WHERE COUNTRY = 'BR' AND LAST_NAME = 'Yes';


-- ULKESI BR OLAN veya Ismide "Metin" olan MÜSTERILERI GETIR
SELECT *
FROM CUSTOMERS
WHERE COUNTRY = 'BR' OR LAST_NAME = 'Metin';


-- ISIM VE SOYISIM KOLANLARINI SEC -  ULKESI BR OLAN veya Ismide "Metin" olan MÜSTERILERI GETIR
SELECT FIRST_NAME, LAST_NAME
FROM CUSTOMERS
WHERE COUNTRY = 'BR' OR LAST_NAME = 'Metin';

-- YASI 27 DEN BÜYÜK OLANLAR
SELECT *
FROM CUSTOMERS
WHERE AGE > '27';

-- YASI 27 DEN BÜYÜK OLANLAR ve ülkesi Almanya olanlar
SELECT *
FROM CUSTOMERS
WHERE AGE > '27' AND my_company_db.CUSTOMERS.COUNTRY = 'DE';

-- Dataset https://www.mockaroo.com
-- https://www.kaggle.com/search?q=company+in%3Adatasets


-- Tabloya 2 tane yeni koloh eklendi.
ALTER TABLE `my_company_db`.`CUSTOMERS`
    ADD COLUMN `EMAIL` VARCHAR(100) NULL AFTER `COUNTRY`,
    ADD COLUMN `GENDER` VARCHAR(1) NULL AFTER `EMAIL`;

insert into my_company_db.CUSTOMERS (FIRST_NAME, LAST_NAME, AGE, COUNTRY, EMAIL, GENDER) values ('Gavan', 'Blann', 72, 'MA', 'gblann0@mashable.com', 'M');


-- Bütün müsterileri listele
-- MUSTERILERI LISTELE
SELECT * FROM my_company_db.CUSTOMERS;


-- ülkesi Almanya olan müsteriler
SELECT *
FROM CUSTOMERS
WHERE my_company_db.CUSTOMERS.COUNTRY = 'DE';


-- ülkesi CANADA olan kadin müsteriler
SELECT *
FROM CUSTOMERS
WHERE my_company_db.CUSTOMERS.COUNTRY = 'CA' AND my_company_db.CUSTOMERS.GENDER = 'F';

-- Sadece Adi ve soyadi olucak ve ülkesi Almanya olan erkek müsteriler
SELECT my_company_db.CUSTOMERS.COUNTRY,my_company_db.CUSTOMERS.FIRST_NAME,LAST_NAME
FROM CUSTOMERS
WHERE my_company_db.CUSTOMERS.COUNTRY = 'DE' AND my_company_db.CUSTOMERS.GENDER = 'M';


-- ÜLKESI ALMANYA VEYA TÜRKIYE OLAN MÜSTERILER
SELECT *
FROM CUSTOMERS
WHERE my_company_db.CUSTOMERS.COUNTRY = 'TR' OR my_company_db.CUSTOMERS.COUNTRY = 'DE';

-- ÜLKESI ALMANYA VEYA TÜRKIYE OLAN MÜSTERILER VE YASI 29 DAN BÜYÜK OLAN MÜSTERILER
SELECT *
FROM CUSTOMERS
WHERE (my_company_db.CUSTOMERS.COUNTRY = 'TR' OR my_company_db.CUSTOMERS.COUNTRY = 'DE') AND AGE > 29;

-- ÜLKESI ALMANYA OLMAYANLAR

SELECT *
FROM CUSTOMERS
WHERE COUNTRY != 'DE'; -- != (NOT)

-- BÜTÜN ÜLKELER TEKIL (HER BIRINDEN BIR TANE VAR)
 SELECT DISTINCT COUNTRY FROM CUSTOMERS;

-- KAC MUSTERI VAR ? SAYISINI VER
SELECT COUNT(*) FROM CUSTOMERS;

-- KAC MÜSTERININ EMAILI VAR?
SELECT COUNT(my_company_db.CUSTOMERS.EMAIL) FROM CUSTOMERS;

-- MÜSTERILERIMIZIN YASLARI TOPLAMI KAC
SELECT SUM(AGE) FROM CUSTOMERS;

-- MÜSTERI KITLEMIN YAS ORTOLAMASI
SELECT AVG(CUSTOMERS.AGE) FROM  CUSTOMERS;

-- EN YASLI MÜSTERIM AS LAKAP/ALIAS Kullanimi
SELECT MAX(AGE) AS EnBüyük
FROM CUSTOMERS;

-- EN GENC MÜSTERIM  - Alias kullanimi birden fazla kelimeden olusursa tirnak icinde -
SELECT MIN(AGE) as "En Kücük"
FROM CUSTOMERS;

-- Lakap ALIAS KULLANIMINDAKI AS KELIMESINI YAZMAK ZORUNLU DEGILDIR

SELECT MIN(AGE) "En Kücük"
FROM CUSTOMERS;

-- ÜLKELERI TEKIL OLARAK LISTELE

SELECT DISTINCT COUNTRY FROM CUSTOMERS;


-- KAC ÜLKE VAR ?
SELECT COUNT(CUSTOMERS.COUNTRY) FROM   CUSTOMERS;

-- HANGI ÜLKEDEN TOPLAM KAC TANE VAR ?

SELECT COUNT(DISTINCT COUNTRY) FROM CUSTOMERS;

-- (Alias/ lakap/ takma isim )
SELECT CUSTOMERS.FIRST_NAME CUS_FIRST, LAST_NAME AS CUS_LAST FROM CUSTOMERS;

-- (Alias/ lakap/ takma isim )

SELECT CUSTOMER_ID CUS_ID,  CUSTOMERS.FIRST_NAME CUS_FIRST, LAST_NAME AS CUS_LAST FROM CUSTOMERS;

SELECT CUSTOMER_ID C_ID, FIRST_NAME C_FIRST, LAST_NAME C_LAST FROM CUSTOMERS;

-- (Alias/ lakap/ takma isim )
SELECT CUSTOMERs.CUSTOMER_ID C_ID, CUSTOMERS.FIRST_NAME C_FIRST, CUSTOMERS.LAST_NAME C_LAST FROM CUSTOMERS;


SELECT c.CUSTOMER_ID C_ID, c.FIRST_NAME C_FIRST, c.LAST_NAME C_LAST FROM CUSTOMERS AS c;

-- LAKAP/ ALIAS HEM KOLONLAR ICIN HEM DE TABLO ICIN
SELECT c.CUSTOMER_ID ID,
       c.FIRST_NAME F,
       c.LAST_NAME L
FROM CUSTOMERS c;

-- ISIM VE SOYISIM BIRLIKTE YAZDIRILACAK
-- CONCAT KOLONLARI BIRLESTIRIR
SELECT CONCAT(FIRST_NAME, ' ', CUSTOMERS.LAST_NAME) FULLNAME FROM CUSTOMERS;

-- Yeni bir Kayit ekle
insert into my_company_db.CUSTOMERS
    (FIRST_NAME, LAST_NAME, AGE, COUNTRY, EMAIL, GENDER)
values
    ('Stan', 'Crisall', 35, 'CN', 'scrisall7@about.me', 'M');

SELECT COUNT(*) FROM CUSTOMERS;


-- UC KAYIT BRDEN EKLEME, bu sekilde kisaltma yapilabiliyor.

insert into
    my_company_db.CUSTOMERS (FIRST_NAME, LAST_NAME, AGE, COUNTRY, EMAIL, GENDER)
values ('Aline', 'Catherick', 55, 'ID', 'acathericka@cornell.edu', 'F'),
       ('Sheryl', 'Claypoole', 100, 'CN', 'sclaypooleb@china.com.cn', 'F'),
       ('Katya', 'Everett', 95, 'PT', 'keverettc@narod.ru', 'F');

SELECT count(*) from CUSTOMERS;

-- ID NUMARASI VERILEN BIR KAYDI SIL
DELETE FROM CUSTOMERS WHERE my_company_db.CUSTOMERS.CUSTOMER_ID = 2;
-- silmede mutlaka WHERE sart olmak zorunda, yoksa bütün kayitlar silinir.
-- silinmis kaydi tekrar silersen, calisir. ama olmayan bir seyi siliyor.

-- VARSAYILAN SIRALAMA 0-9 / A-Z VE ID kolonuna (Primary Key e ) göre yapilir.
SELECT * FROM CUSTOMERS;

-- FIRST_NAME E GÖRE SIRALAMA VARSAYILAN (ASC)
SELECT *
FROM CUSTOMERS
ORDER BY FIRST_NAME; -- ORDER BY FIRST_NAME ASC;

-- FIRST_NAME E GÖRE SIRALAMA Z DEN A YA  (DESC) 9-0 / Z-A
SELECT *
FROM CUSTOMERS
ORDER BY FIRST_NAME DESC ;


-- MÜSTERILERI EN KÜCÜKTEN EN BÜYÜGE DOGRU SIRALAMA
SELECT *
FROM CUSTOMERS
ORDER BY AGE ASC ;

-- MÜSTERILERI EN BÜYÜKTEN EN KÜCÜKTEN DOGRU SIRALAMA
SELECT *
FROM CUSTOMERS
ORDER BY AGE DESC ;

-- ÜLKELERI Z DEN A YA SIRALA (TERSTEN) VE MÜSTERILERI YASA GÖRE SIRALA
SELECT *
FROM CUSTOMERS
ORDER BY COUNTRY DESC, AGE DESC ;

-- Ülkelerin isimlerini al ve kisi sayisina göre COKTAN AZA GÖRE sirala
-- BURADA GROUP BY KUllanmaliyiz.
-- order by, group by dan sonra gelir. Order by i her zaman en sona .
-- Önce gruplama isini bitirip, sonra siralama
select DISTINCT CUSTOMERS.COUNTRY, COUNT(*) AS KISI_SAYISI
FROM CUSTOMERS
GROUP BY COUNTRY
ORDER BY KISI_SAYISI DESC;

-- ULKELERIN ISIMLERINI AL
-- VE KISI SAYISINA GÖRE SIRALA
-- YASI 50 DEN BÜYÜK MÜSTERILER ICIN VE RUSYADAN KAC KISI VAR:
SELECT COUNTRY, COUNT(*) AS KISI_SAYISI
FROM CUSTOMERS
WHERE AGE > 50
GROUP BY COUNTRY
HAVING my_company_db.CUSTOMERS.COUNTRY = 'RU' -- GRUBUN SARTI
ORDER BY KISI_SAYISI; -- ; ILLAKI OLMAK ZORUNDA DEGIL

-- ULKELERIN ISIMLERINI AL
-- VE KISI SAYISINA GÖRE TERSTEN SIRALA
-- YASI 15 DEN BÜYÜK MÜSTERILER ICIN VE ALMANYADAN OLMAYAN MÜSTERILERIN SAYISI:
SELECT COUNTRY, COUNT(COUNTRY) AS KISI_SAYISI
FROM CUSTOMERS
WHERE AGE > 15
GROUP BY COUNTRY
HAVING NOT COUNTRY = 'DE' -- HAVING COUNTRY != 'DE'
ORDER BY KISI_SAYISI DESC;

-- TRUNCATE, VERI TABANININ ICINDEKI HER SEYI SILIYOR. SAYACI DAHI SILIYOR
-- TABLO ILK HALINE DÖNER . BÜTÜN KOLONLAR DURUR AMA ICERISINDE HIC BIR BILGI KALMAZ
-- DELETE ILE SILDIGIMIZDE SAYAC KALIYOR.
TRUNCATE my_company_db.CUSTOMERS;


-- DROP TABLE, ISE TABLOYU KOMPLE SILIYOR
DROP TABLE my_company_db.CUSTOMERS;

-- UPDATE SART KOSMAK ZORUNDAYIZ, YOKSA BÜTÜN KAYITLARI GÜNCELLERIZ
-- GÜNCELLEMEDE VE SILMEDE SART KISMI COK ÖNEMLIDIR

UPDATE my_company_db.CUSTOMERS
SET
    FIRST_NAME = 'Hakan',
    LAST_NAME = 'Metin'
WHERE CUSTOMER_ID = 3;

select * from CUSTOMERS;

UPDATE my_company_db.CUSTOMERS
SET
    FIRST_NAME = 'Hakan',
    LAST_NAME = 'Metin'
WHERE COUNTRY = 'PL';

select * from CUSTOMERS;